Algoritmo "conversor_monetário"

// Disciplina  : Curso de Lógica de Programação [Algoritmo]
// Professor   : Gustavo Guanabara
// Descrição   : Aula 6 – Exercícios de Algoritmo Resolvidos
// Autor(a)    : Thiago Balbo Batista
// Ano         : 2020

var
   Reais, Dolar: Real
inicio
// Calculando a conversão de câmbio:

Escreval("Quantos Reais eu tenho? ")
Leia(Reais)
Dolar <- Reais/5.36
Escreva("Então eu tenho US$ ", Int(Dolar))

fimalgoritmo


