algoritmo "Combinação"

// Disciplina  : Curso de Lógica de Programação[Algoritmo]
// Professor   : Gustavo Guanabara
// Descrição   : Aula 12 – Procedimentos
// Autor(a)    : Thiago Balbo Batista
// Ano         : 2020

var
   C1, C2: Inteiro
inicio
// Mostrar todas as combinações dos números de 1 a 3:

   Para C1 <- 1 ate 3 faca
        Para C2 <- 1 ate 3 faca
             Escreval(C1, C2)
        FimPara
   FimPara
   
fimalgoritmo
